import os
import logging

from flask import Flask, request, abort, render_template
from email_validator import validate_email, EmailNotValidError
import MySQLdb
from itsdangerous import URLSafeSerializer, BadSignature, SignatureExpired

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
app = Flask(__name__)
app.config['SECRET_KEY'] = os.environ.get('FLASK_SECRET_KEY')  # must be set
DB_HOST     = os.environ.get('DB_HOST', 'localhost')
DB_USER     = os.environ.get('DB_USER')    # least-privilege account
DB_PASS     = os.environ.get('DB_PASS')
DB_NAME     = os.environ.get('DB_NAME')
UNSUBSCRIBE_TOKEN_SALT = 'unsubscribe-salt'  # constant
UNSUBSCRIBE_TOKEN_MAX_AGE = 60 * 60 * 24     # 24 hours

# Basic logging setup
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Token serializer
serializer = URLSafeSerializer(app.config['SECRET_KEY'], salt=UNSUBSCRIBE_TOKEN_SALT)

# -----------------------------------------------------------------------------
# Database utility
# -----------------------------------------------------------------------------
def get_db_connection():
    """Return a new MySQLdb connection using credentials from env."""
    return MySQLdb.connect(host=DB_HOST,
                           user=DB_USER,
                           passwd=DB_PASS,
                           db=DB_NAME,
                           charset='utf8mb4',
                           cursorclass=MySQLdb.cursors.DictCursor,
                           connect_timeout=5)

# -----------------------------------------------------------------------------
# Helper: generate unsubscribe token (to be used when sending the email)
# -----------------------------------------------------------------------------
def generate_unsubscribe_token(email):
    """
    Create a time-limited, signed token embedding the normalized email.
    Include this in the unsubscribe URL sent to the user.
    """
    # WARNING: do not expose this function endpoint publicly
    return serializer.dumps({'email': email})

# -----------------------------------------------------------------------------
# /unsubscribe endpoint
# -----------------------------------------------------------------------------
@app.route('/unsubscribe')
def unsubscribe():
    """
    Securely process an unsubscribe request.
    Expects two GET parameters:
      - email: the user's email address
      - token: a signed token generated by generate_unsubscribe_token(email)
    """
    raw_email = request.args.get('email', '').strip()
    raw_token = request.args.get('token', '').strip()

    # 1) Basic presence check
    if not raw_email or not raw_token:
        logger.warning("Missing email or token in unsubscribe request")
        # Use uniform abort message to avoid info leakage
        abort(400, description="Invalid request")

    # 2) Email validation & normalization
    try:
        valid = validate_email(raw_email)
        email = valid.email  # E.g. lowercased, properly formatted
    except EmailNotValidError:
        logger.warning("Invalid email format")
        abort(400, description="Invalid request")

    # 3) Token validation
    try:
        data = serializer.loads(raw_token, max_age=UNSUBSCRIBE_TOKEN_MAX_AGE)
    except SignatureExpired:
        logger.info("Expired unsubscribe token for %s", email)
        abort(400, description="Unsubscribe link expired")
    except BadSignature:
        logger.warning("Bad unsubscribe token")
        abort(400, description="Invalid request")

    # 4) Ensure token email matches the requested email
    token_email = data.get('email')
    if token_email != email:
        logger.warning("Token email mismatch: token %r vs query %r",
                       token_email, email)
        abort(400, description="Invalid request")

    # 5) Perform the unsubscribe in the database
    try:
        conn = get_db_connection()
        with conn:  # auto-commits or rolls back on exception
            cursor = conn.cursor()
            # Parameterized query to prevent SQL injection
            cursor.execute(
                "DELETE FROM subscribers WHERE email = %s",
                (email,)
            )
            # rowcount may be 0 if the email was not present;
            # we do NOT distinguish this case in the response
            # to avoid user-enumeration attacks.
        logger.info("Processed unsubscribe for %s (rows affected: %d)",
                    email, cursor.rowcount)
    except MySQLdb.Error:
        logger.exception("Database error while unsubscribing %s", email)
        # 500 Internal Server Error, but with generic message
        abort(500, description="An internal error occurred")

    # 6) Render a generic success page (200 OK)
    return render_template('unsubscribe_success.html'), 200


# -----------------------------------------------------------------------------
# Note on sending the unsubscribe link (outside of this snippet)
# -----------------------------------------------------------------------------
# When you send your mailing, compose a link of the form:
#    https://yourdomain.com/unsubscribe?email={urlencoded_email}&token={urlencoded_token}
# where token = generate_unsubscribe_token(normalized_email)
# Do NOT expose generate_unsubscribe_token as a web endpoint.
# -----------------------------------------------------------------------------